// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr4TbabSYxlZoe6ASQzvAHidvx9xolwug',
    appId: '1:199634025012:web:8d522e2d3a4070a9272861',
    messagingSenderId: '199634025012',
    projectId: 'xgen-e83bd',
    authDomain: 'xgen-e83bd.firebaseapp.com',
    storageBucket: 'xgen-e83bd.firebasestorage.app',
    measurementId: 'G-PY3LKN21VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA3WWJjFMWFqGw0B_acxztj6kTsvwlruQ',
    appId: '1:199634025012:android:2ba99040f64ddfc2272861',
    messagingSenderId: '199634025012',
    projectId: 'xgen-e83bd',
    storageBucket: 'xgen-e83bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAju2mw7vH3eJTM1lsIKvWWwl5GYXtzY-I',
    appId: '1:199634025012:ios:0a8e43bc3a9b7e15272861',
    messagingSenderId: '199634025012',
    projectId: 'xgen-e83bd',
    storageBucket: 'xgen-e83bd.firebasestorage.app',
    iosBundleId: 'com.xgen.xgen',
  );

}